# Generated by Django 3.2.6 on 2021-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(max_length=255)),
                ('shorten_url', models.CharField(blank=True, max_length=15)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
