# Generated by Django 3.2.6 on 2021-08-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='original_url',
            field=models.URLField(max_length=255, unique=True, verbose_name='Original url'),
        ),
        migrations.AlterField(
            model_name='links',
            name='shorten_url',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='Short link'),
        ),
    ]
