# Generated by Django 3.2.6 on 2021-08-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20210810_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links',
            name='original_url',
            field=models.URLField(max_length=255, verbose_name='Original url'),
        ),
        migrations.AlterField(
            model_name='links',
            name='shorten_url',
            field=models.CharField(blank=True, db_index=True, max_length=25, verbose_name='Short link'),
        ),
    ]
